[package]
name = "pg_replicate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "bigquery"
required-features = ["bigquery"]

[[example]]
name = "duckdb"
required-features = ["duckdb"]

[[example]]
name = "stdout"
required-features = ["stdout"]

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
duckdb = { workspace = true, optional = true }
futures = { workspace = true }
gcp-bigquery-client = { workspace = true, optional = true, features = [
    "rust-tls",
    "aws-lc-rs",
] }
pin-project-lite = { workspace = true }
postgres-protocol = { workspace = true }
prost = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-postgres = { workspace = true, features = ["runtime", "with-chrono-0_4"] }
tracing = { workspace = true, default-features = true }

[dev-dependencies]
clap = { workspace = true, default-features = true, features = [
    "std",
    "derive",
] }
rustls = { workspace = true, features = ["aws-lc-rs", "logging"] }
tracing-subscriber = { workspace = true, default-features = true, features = [
    "env-filter",
] }

[features]
bigquery = ["dep:gcp-bigquery-client", "dep:prost"]
duckdb = ["dep:duckdb"]
stdout = []
default = []
